spring.application.name=rules

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

aaa.bbb=test
# ??????
stock.result.json.path=D:/development/github/stockapi/result_json/
stock.hm.top_inst.path=D:/development/github/tushare/111/tushare/hm/top_inst/
stock.all_stocks.csv.path=D:/development/github/stockapi/all_stocks.csv
stock.moneyflow_dc.path=D:/development/github/tushare/111/tushare/moneyflow/data/moneyflow_dc/