spring.application.name=rules

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

aaa.bbb=test

stock.analysis.system.path=D:/development/github/tushare/111/gitee_stockapi/
stock.datasource.build.system.path=D:/development/github/tushare/111/gitee_zuktushare/