spring.application.name=rules

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

aaa.bbb=test
# ??????
stock.analysis.system.path=D:/development/github/stockapi/
stock.hm.top_inst.path=D:/development/github/tushare/111/tushare/hm/top_inst/
stock.moneyflow_dc.path=D:/development/github/tushare/111/tushare/moneyflow/data/moneyflow_dc/