package zuk

import org.apache.commons.codec.digest.DigestUtils
import org.scalatest.funsuite.AnyFunSuite

import java.io.{File, FileInputStream, IOException}
import java.nio.file.{Files, Path, Paths}
import java.util
import java.util.concurrent.atomic.AtomicInteger
import scala.jdk.CollectionConverters.*

class ClassCompareTest extends AnyFunSuite {

  @throws[IOException]
  def getAllFiles(path: String): java.util.List[Path] = {
    val rootPath = Paths.get(path)
    val paths = Files.walk(rootPath)
    val ls = paths.toList.asScala.filter(p=>p.toFile.isFile).map(p=>{
      val relativizePath = rootPath.relativize(p)
      val str = relativizePath.toString
      relativizePath
    }).toList.sortBy(e=>(e.toString)).asJava
    ls
  }

  test("class比较") {
    val jarClassPath = "C:\\Users\\5132\\.m2\\repository\\zuk\\cbsast\\merge-93\\2.0.0\\merge-93-2.0.0\\cn"
    val jarClassPathFiles = getAllFiles(jarClassPath)
    println(s"${jarClassPathFiles.size()}")
    val jarClassPathMap = new util.HashMap[String, Path]()
    jarClassPathFiles.asScala.foreach(p=>{
      jarClassPathMap.put(p.toString, p)
    })

    val targetClassPath = "D:\\development\\github\\webb\\web\\cobot-parsers\\target\\classes\\cn"
    val targetClassPathFiles = getAllFiles(targetClassPath)
    println(s"${targetClassPathFiles.size()}")
    val targetClassPathMap = new util.HashMap[String, Path]()
    targetClassPathFiles.asScala.foreach(p=>{
      targetClassPathMap.put(p.toString, p)
    })

    val num = new AtomicInteger(0)
    val num1 = new AtomicInteger(0)
    val num2 = new AtomicInteger(0)
    jarClassPathFiles.asScala.filter(p=> !p.toString.contains("utils\\linetracker")  ).filter(p=>{
      this.ignoreFiles().filter(f=>f.endsWith(p.toString)).size == 0
    }).foreach(p=>{
      val path = targetClassPathMap.get(p.toString)
      if(path==null){
        println(s"${num.addAndGet(1)}缺少文件：cn\\${p.toString}")
      }
      else {
        val p1 = jarClassPath + "\\" + p.toString
        val fis1 = new FileInputStream(p1)
        val md5_1 = DigestUtils.md5Hex(fis1)

        val p2 = targetClassPath  + "\\" + path.toString
        val fis2 = new FileInputStream(p2)
        val md5_2 = DigestUtils.md5Hex(fis2)


        if(!md5_1.equals(md5_2)){
          println(s"${num1.addAndGet(1)}文件不相同：${p2}")
          val javaPath = if(p2.contains("$")){
            s"D:\\development\\github\\webb\\web\\cobot-parsers\\src\\main\\java\\cn\\${path.toString.split("\\$")(0)}.java"
          }
          else {
            s"D:\\development\\github\\webb\\web\\cobot-parsers\\src\\main\\java\\cn\\${path.toString.replaceAll(".class",".java")}"
          }
//          val javaPath = s"D:\\development\\github\\webb\\web\\cobot-parsers\\src\\main\\java\\cn\\${path.toString.replaceAll(".class",".java")}"
          if(new File(javaPath).exists()){
            println(s"           ${javaPath}，${new File(javaPath).exists()}")
//            new File(javaPath).delete()
          }
        }
        else {
          //println(s"${num2.addAndGet(1)}文件相同")
        }
      }
    })

    println()
  }

  private def ignoreFiles(): Set[String] = {
    Set[String](
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTProblemOwner.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTProblemExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTProblemDeclaration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTPointer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTOperatorName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTName.class",   //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTNameBase$RecursionResolvingBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTNameBase.class",   //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTNewExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTNullStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTKnRFunctionDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTLabelStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTLambdaExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTLinkageSpecification.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTLiteralExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTInitializerList.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTImplicitName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTIfStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTIfStatement$N.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTIdExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTGotoStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTIdExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTGotoStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTExpressionList.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTExpressionStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTFieldDesignator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTFieldReference.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTFunctionCallExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTFunctionDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTFunctionDefinition$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTFunctionDefinition.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTDoStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTDesignatedInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTDeleteExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTDefaultStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTDeclarator.class",  //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTDeclarationStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTConversionName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTContinueStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTConstructorInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTConditionalExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTCompoundStatementExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTCompoundStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTCompositeTypeSpecifier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTCatchHandler.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTCastExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTCaseStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTBreakStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTBinaryTypeIdExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTBinaryExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTBinaryExpression$N.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTArraySubscriptExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTArrayRangeDesignator.class",  //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTArrayDesignator.class",  //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTArrayDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguousTemplateArgument.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguousStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguousSimpleDeclaration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguousParameterDeclaration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguousDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguousCondition.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTAmbiguityResolver.class", //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\AbstractCPPClassSpecializationScope.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\AbstractCPPClassSpecializationScope$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\ASTBindingResolver.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CVisitor$CollectDeclarationsAction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CVisitor$CollectProblemsAction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CVisitor$CollectReferencesAction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\GNUCSourceParser.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\ICFunction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\ICInternalBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\ToStringUtility.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CVariable.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CVariable$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CTypedef.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CStructure.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CStructure$CStructureProblem.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CQualifierType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CPointerType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CParameter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CParameter$CParameterProblem.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CNodeFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CLabel.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CEnumeration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CEnumerator$CEnumeratorProblem.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CEnumerator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CExternalFunction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CExternalVariable.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CField$CFieldProblem.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CField.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CFunction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CFunctionType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CKnRParameter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CBuiltinParameter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CBasicType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CBasicType$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CArrayType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTUnaryExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTypeIdInitializerExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTypeIdExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTypeId.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTSwitchStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTSimpleDeclaration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CBuiltinParameter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CBasicType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CBasicType$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CArrayType.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTUnaryExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTypeIdInitializerExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTypeIdExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTypeId.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTSwitchStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTSimpleDeclaration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTProblemExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTLiteralExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTKnRFunctionDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTInitializerList.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTIdExpression.class", //xXXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTFunctionDefinition.class", //xXXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTFunctionDefinition$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTFunctionDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTFunctionCallExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTFieldReference.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTExpressionStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTExpressionList.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTEnumerationSpecifier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTDoStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTDesignatedInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTDeclarationStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTConditionalExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTCompoundStatementExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTCompoundStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTCompositeTypeSpecifier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTCastExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTBinaryExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTBinaryExpression$N.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTBaseDeclSpecifier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTArraySubscriptExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTArrayDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTAmbiguousParameterDeclaration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTAmbiguousDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\Value.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\Value$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\Value$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\SolveSpecialBindingUtility.class", //XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\SizeofCalculator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\SizeofCalculator$SizeAndAlignment.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\SizeofCalculator$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ProblemType.class", //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ProblemFunctionType.class", //xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ProblemBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\GCCBuiltinSymbolProvider.class", //XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\FindNodeForOffsetAction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\DeclarationOptions.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\DebugASTVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\FindNodeForOffsetAction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\DeclarationOptions.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\DebugASTVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ArithmeticConversion.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ArithmeticConversion$Rank.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ArithmeticConversion$Domain.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ArithmeticConversion$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$BinaryOperator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$CastAmbiguityMarker.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$CastExprCtx.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$Decl.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$ExprKind.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$FoundAggregateInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser$ITemplateIdStrategy.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\AbstractGNUSourceCodeParser.class", //XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTQueries.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTQueries$NameSearch.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTNode.class", // xxx
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTNodeSelector.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTInternal.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTEqualsInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTEnumerator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTCopyLocation.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTAmbiguousNode.class",  // XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTAmbiguousNode$NameCollector.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTAmbiguousBinaryVsCastExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\ast\\tag\\TaggerDescriptor.class",  // XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\ast\\tag\\TaggerDescriptor$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\ast\\tag\\TagManager.class", // XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\SavedCodeReaderFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\PartialWorkingCopyCodeReaderFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\Linkage.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\InternalASTServiceProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\AbstractCodeReaderFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\UserVarSupplier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\UserDefinedVariableSupplier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\UserDefinedVariableSupplier$VarKey.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\EnvironmentVariableSupplier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\EnvironmentVariableSupplier$EnvVarMacro.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\EnvironmentVariableSupplier$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\EclipseVariablesVariableSupplier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\EclipseVariablesVariableSupplier$EclipseVarMacro.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\EclipseVariablesVariableSupplier$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\DefaultVariableContextInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\CdtVariableManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\CdtVariableManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\cdtvariables\\CdtMacroSupplier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\util\\Param.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\util\\EBinaryCustomFuncDef.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\util\\BinaryCustomFuncDef.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\instrumentor\\BinaryUtility.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\AddExtraCode.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\BinaryDecompiler$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\BinaryDecompiler$IDAMode.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\BinaryDecompiler.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\BlockSummary.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\ComputeStringSimilarDegree.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\DeleteExtraCode.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\DeleteExtraCodeByMain.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\decompiler\\DeleteExtraCodeRewrite.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\converter\\AddressToLineInAsmFile.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\converter\\BinaryASTVisiter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\converter\\GetAddressToline.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\converter\\HandleAsmFile.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\binary\\converter\\HandleMapJson.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\XmlUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\UNCPathConverterImpl.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\SystemBuildConsole.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\SystemBuildConsole$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\SystemBuildConsole$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\StatusUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\ProblemMarkerFilterManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\ProblemMarkerFilterDesc.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\ProblemMarkerFilterDesc$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\PositionTrackerManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\PositionTracker.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\PositionTracker$Node.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\PathEntryVariableResolver.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\MinGW.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\LocalProjectScope.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\Cygwin.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\ConfigurationInfoVariableResolver.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CdtVarPathEntryVariableManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CdtVarPathEntryVariableManager$VarSupplier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CdtVarPathEntryVariableManager$VarSubstitutor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CdtVarPathEntryVariableManager$VarContextInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CdtVarPathEntryVariableManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CCoreInternals$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CCoreInternals.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CCorePreferenceInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CDTLogWriter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CExtensionDescriptor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\COwner.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\COwnerConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CContentTypes.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptorManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptorManager$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptorManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptor$SerializingJob.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptor$CConfigBaseDescriptorExtensionReference.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptor$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\CConfigBasedDescriptor$1$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\BuildRunnerHelper.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\XmlStorageElement.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\UtilMessages.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\ResourceChangeHandlerBase.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\ResourceChangeHandlerBase$DeltaVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\ResourceChangeHandlerBase$IResourceMoveHandler.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$VarSubstitutor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$ResourceInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$ResolvedEntry.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$ReferenceSettingsInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$RcDesInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$PathEntryValueInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$PathEntryKyndStore.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$PathEntryComposer.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$PathEntryCollector.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$PathEntryCollector$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$LangEntryInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\PathEntryTranslator$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\LanguageSettingEntriesSerializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\CSettingEntryFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\CExtensionUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\CDataUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\CDataUtil$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\util\\CDataSerializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\CFolderDescriptionCache.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\CFileDescriptionCache.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CResourceDataContainer.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CResourceDataContainer$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CDefaultFolderData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CDefaultFileData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CDataFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\PathEntryConfigurationDataProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\PathEntryConfigurationDataProvider$PathEntryLanguageData.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\PathEntryConfigurationDataProvider$PathEntryFolderData.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\PathEntryConfigurationDataProvider$PathEntryFileData.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\PathEntryConfigurationDataProvider$PathEntryDataFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\PathEntryConfigurationDataProvider$CfgData.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\ExtensionContainerFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\ExtensionContainerFactory$NullProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\ExtensionContainerFactory$CExtensionSettingProviderDescriptor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\ExtensionContainerFactory$CESContainer.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\CConfigurationDescriptionCache.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\settings\\model\\CBuildSettingCache.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CDefaultConfigurationDataProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CDefaultConfigurationData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\impl\\CDefaultBuildData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\CExternalSettingProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\CConfigurationDataProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\CConfigurationData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\extension\\CBuildData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\XmlStorageUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\CProjectDescriptionEvent.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\CLibraryFileEntry.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\settings\\model\\CConfigurationStatus.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\ScannerProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\ResourcesUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\RefreshScopeManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\RefreshScopeManager$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\RefreshScopeManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\RefreshScopeManager$1$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\RefreshExclusion.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\RefreshExclusion$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\FileStorage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\ExclusionInstance.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\ExclusionInstance$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\resources\\ACBuilder.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\HashTable.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\CommentUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\CharArrayUtils.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\CharArrayObjectMap.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\CharArrayObjectMap$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\CharArrayMap.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\CharArrayMap$Key.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ArrayUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ASTPrinter.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ASTPrinter$PrintVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ASTPrinter$PrintProblemsVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ArrayUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ASTPrinter$PrintProblemsVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ASTPrinter$PrintVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\util\\ASTPrinter.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\Keywords.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\ParserUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\IToken$ContextSensitiveTokenType.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\IToken.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\MacroExpander$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\MacroExpander$AbortMacroExpansionException.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\MacroExpander$ExpansionBoundary.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\MacroExpander$TokenSource.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\MacroExpander.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\IProblem.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$3.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$FileComparator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$IncludeResolution.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$MacroDictionary.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor$TokenSequence.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\CPreprocessor.class",  //XXX
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\ILocationResolver.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\LocationMap.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\InternalFileContent$FileVersion.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\InternalFileContent$InclusionKind.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\InternalFileContent.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\FileContent.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\CodeReaderCache$UpdateCodeReaderCacheListener$RemoveCacheJob.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\CodeReaderCache$UpdateCodeReaderCacheListener.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\parser\\CodeReaderCache.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\util\\CElementBaseLabels.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\ILanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\LanguageManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\LanguageManager$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\LanguageManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\model\\CProject.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMProject.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\ICProject.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\ICModelMarker.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\CoreModelUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\CoreModel.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\CModelException.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\AssemblyLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\ICModelMarker.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\CoreModelUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\CoreModel.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\CModelException.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\AssemblyLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\language\\settings\\providers\\ScannerDiscoveryLegacySupport.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\language\\settings\\providers\\LanguageSettingsSerializableProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\language\\settings\\providers\\LanguageSettingsManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\language\\settings\\providers\\LanguageSettingsBaseProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\language\\ProjectLanguageConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\provider\\ReadOnlyPDOMProviderBridge.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\provider\\IIndexFragmentProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\provider\\IIndexProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\export\\ExportIndexFileInfoMatcher.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\export\\ExternalExportProjectProvider$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\export\\ExternalExportProjectProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\export\\AbstractExportProjectProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\URIRelativeLocationConverter.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\ResourceContainerRelativeLocationConverter.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IndexLocationFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IndexFilter$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IndexFilter$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IndexFilter.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMASTProcessorDesc$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMASTProcessorDesc.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IPDOMASTProcessor$Abstract.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IPDOMASTProcessor.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$3.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$4.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$5.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$6$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$6.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$7$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$7.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$8.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$9$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$9.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager$PCL.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\PDOMManager.class",   /// XXX，变动很大，是不是版本不对？
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IIndexName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IIndexFragmentName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMMacroDefinitionName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMMacroReferenceName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMName.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMMacro.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\WritableCIndex.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IndexFileSet.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IndexFileSet$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IIndexMacro.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IIndexFileSet.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMFile$Comparator.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMFile$Finder.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\pdom\\dom\\PDOMFile.class", //XXX 仅完成一半
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IIndexFragmentFile.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IIndexFile.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IIndexBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\EmptyCIndex.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IWritableIndex.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IWritableIndex$IncludeInformation.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\IWritableIndex.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\CIndex$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\CIndex$NameKey.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\index\\CIndex.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\index\\IIndex.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\formatter\\DefaultCodeFormatterConstants.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\formatter\\DefaultCodeFormatterOptions.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\formatter\\IndentManipulation.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\errorparsers\\ErrorParserNamedWrapper.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\errorparsers\\ErrorPattern.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\errorparsers\\RegexErrorPattern.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\rewrite\\MacroExpansionExplorer.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\rewrite\\MacroExpansionExplorer$IMacroExpansionStep.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\rewrite\\ASTRewrite.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\rewrite\\ASTRewrite$Operation.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\rewrite\\ASTRewrite$CommentPosition.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\rewrite\\ASTRewrite$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\cpp\\AbstractCPPParserExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\cpp\\GPPParserExtensionConfiguration.class",  //XXX
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\cpp\\GPPScannerExtensionConfiguration.class", //XXX
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\cpp\\POPCPPParserExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\cpp\\POPCPPScannerExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\c\\GCCParserExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\c\\GCCScannerExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\ISourceCodeParser.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\GNUScannerExtensionConfiguration$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\GNUScannerExtensionConfiguration$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\GNUScannerExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\IScannerExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\AbstractScannerExtensionConfiguration$MacroDefinition.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\AbstractScannerExtensionConfiguration.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\model\\AbstractLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\AbstractCLikeLanguage$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\AbstractCLikeLanguage$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\AbstractCLikeLanguage$NameCollector.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\parser\\AbstractCLikeLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLElement.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLEntityResolver.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLFactoryWithLocator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLFileLocation.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLSAXContentHandler.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLSAXReader.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\xml\\XMLUnit.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\make\\MakeFileLocation.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\gnu\\cpp\\ICPPASTKnRFunctionDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\gnu\\cpp\\IGPPASTArrayRangeDesignator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\gnu\\c\\GCCLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\gnu\\cpp\\GPPLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPNodeFactory.class",   //XXX
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPExternalFunction.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPExternalBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTNewExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTForStatement.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTFieldDesignator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTDesignator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTDesignatedInitializer.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTArrayDesignator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\cpp\\ICPPASTArraySubscriptExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\c\\ICField.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\c\\ICParameter.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\c\\ICVariable.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\c\\ICExternalFunction.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\c\\ICExternalBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IValue.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IType.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\ITypedef.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPScope$CPPScopeProblem.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPScope.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CScope$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CScope$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CScope$CollectNamesAction.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CScope.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IScope.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IScope$ScopeLookupData.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IProblemBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\INodeFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IMacroBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IExternalFunction.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IExternalBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTTypeId.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\cpp\\CPPASTTranslationUnit.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\c\\CASTTranslationUnit.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTTranslationUnit.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\dom\\parser\\ASTTranslationUnit$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTTranslationUnit.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTTranslationUnit$IDependencyTree.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTTranslationUnit$IDependencyTree$IASTInclusionNode.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTPreprocessorMacroDefinition.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTNode.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTNode$CopyStyle.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTName.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTIdExpression.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTFunctionDefinition.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTFunctionDeclarator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTFileLocation.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTNodeLocation.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTEnumerationSpecifier$IASTEnumerator.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTEnumerationSpecifier.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\core\\parser\\scanner\\ASTComment.class", //XXX 从这里开始下面，是纯逆向
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\IASTComment.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\ASTTypeUtil$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\ASTTypeUtil.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\CountedBinding.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\ASTVisitor.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\ASTNameCollector.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\ast\\ASTNodeProperty.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\IPDOMManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\IPDOMIndexer.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\IPDOMIndexerTask.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\IASTServiceProvider$UnsupportedDialectException.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\IASTServiceProvider.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\dom\\CDOM.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\cdtvariables\\CdtVariableStatus.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\ToolFactory.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\ProblemMarkerInfo.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\ErrorParserManager$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\ErrorParserManager.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CommandLauncher.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CProjectNature.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCorePreferenceConstants.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCorePlugin$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCorePlugin$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCorePlugin$NullConsole$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCorePlugin$NullConsole.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCorePlugin.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\GASErrorParser.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$3.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$4.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$5.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$6.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$7.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$8.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$9.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$10.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$11.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$12.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$13.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$14.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$15.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$16.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$17.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$18.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$19.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$20.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$21.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$22.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$23.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$24.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$25.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$26.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$27.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$28.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$29.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser$30.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\MakeErrorParser.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\VCErrorParser.class",
      "cn\\net\\cobot\\parsers\\cparser\\internal\\errorparsers\\VCErrorParser$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ParserUtility.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\MakeFileParser.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CXXCheckParamConverter.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CheckConfig.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CheckParam$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CheckParam$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CheckParam.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CobotParserConfig.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$BitFieldInterpretation.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$CharInterpretation.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$IntrinsicType_PtrdiffT.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$IntrinsicType_SizeT.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$IntrinsicType_WcharT.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$RightShiftBehaviour.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig$TypeSizeAndAlignment.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\CompilerConfig.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\LostFileHeader.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ProgrammingLanguage$1.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ProgrammingLanguage$2.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ProgrammingLanguage$3.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ProgrammingLanguage$4.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ProgrammingLanguage$5.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\ProgrammingLanguage.class",
      "cn\\net\\cobot\\parsers\\cparser\\common\\TypeCompare.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\AbstractCExtension.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CCProjectNature.class",
      "cn\\net\\cobot\\parsers\\cparser\\core\\CConventions.class"
    )
  }

}
